name:                stack-compat
version:             0.1.0.0
synopsis:            Build old Stack 1 projects with Stack 2
homepage:            https://github.com/yairchu/stack-compat#readme
license:             BSD3
author:              Yair Chuchem
maintainer:          yairchu at gmail dot com
copyright:           2019 Yair Chuchem
category:            Web
extra-source-files:
- README.md

dependencies:
  - base
  - bytestring
  - directory
  - lens
  - lens-aeson
  - process
  - vector
  - yaml

executables:
  stack-compat:
    source-dirs:      src
    main:             Main.hs
